name: test
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distro: jazzy
      - name: Build
        run: |
          # 依存関係をインストールし、ビルドする
          colcon build
      - name: Check package
        run: |
          # ビルドした環境を読み込んでから、コマンドが存在するか確認する
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          ros2 run robosys2025 cpu_publisher --help
