name: test
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distro: jazzy
      - name: Build
        run: |
          colcon build
